"""Lane registry, king state, and benchmark snapshot persistence.

This module was a single 550-line file. It is now a NARROW FACADE over four modules that each answer
one question -- what a lane is (`models`), where it lives (`paths`), how it is encoded (`codecs`),
and how it is read and written (`store`).

The facade is not decoration. `kata-sn60` imports from ``kata.state.lanes`` directly and is packaged
and deployed on its own schedule, so every name that was importable here has to stay importable
here. Prefer the specific modules in new code.
"""

from __future__ import annotations

from kata.state.lanes.codecs import (
    float_list_map,
    int_map,
    maybe_load,
    optional_string,
    parse_benchmark_snapshot,
    parse_challenge_state,
    parse_lane_king_state,
    parse_lane_metadata,
    parse_pack_registry,
    parse_promotion_record,
    read_json,
    read_subnet_pack_field,
    require_bool,
    serialize_lane_metadata,
    serialize_pack_registry,
    string_list,
    write_json_dataclass,
)
from kata.state.lanes.models import (
    BENCHMARK_SNAPSHOT_FILENAME,
    BENCHMARK_SNAPSHOT_SCHEMA_VERSION,
    CHALLENGE_STATE_FILENAME,
    CHALLENGE_STATE_SCHEMA_VERSION,
    KING_STATE_FILENAME,
    KING_STATE_SCHEMA_VERSION,
    LANE_METADATA_FILENAME,
    LANE_METADATA_SCHEMA_VERSION,
    LANES_DIRNAME,
    PACK_REGISTRY_FILENAME,
    PACK_REGISTRY_SCHEMA_VERSION,
    PROMOTION_RECORD_FILENAME,
    PROMOTION_RECORD_SCHEMA_VERSION,
    BenchmarkSnapshotState,
    ChallengeState,
    EvaluatorLaneMetadata,
    EvaluatorLaneState,
    LaneKingState,
    PackRegistry,
    PackRegistryEntry,
    PromotionRecord,
    validate_lane_id,
)
from kata.state.lanes.paths import (
    benchmark_snapshot_path,
    challenge_state_path,
    lane_king_state_path,
    lane_metadata_path,
    pack_registry_path,
    promotion_record_path,
    resolve_lane_root,
    resolve_lanes_root,
)
from kata.state.lanes.store import (
    discover_active_lane_ids,
    list_lane_ids,
    load_benchmark_snapshot,
    load_challenge_state,
    load_evaluator_lane_state,
    load_lane_king_state,
    load_lane_metadata,
    load_pack_registry,
    load_promotion_record,
    sync_pack_registry,
    upsert_pack_registry_entry,
    write_benchmark_snapshot,
    write_challenge_state,
    write_lane_king_state,
    write_lane_metadata,
    write_pack_registry,
    write_promotion_record,
)

__all__ = [
    "BENCHMARK_SNAPSHOT_FILENAME",
    "BENCHMARK_SNAPSHOT_SCHEMA_VERSION",
    "BenchmarkSnapshotState",
    "CHALLENGE_STATE_FILENAME",
    "CHALLENGE_STATE_SCHEMA_VERSION",
    "ChallengeState",
    "EvaluatorLaneMetadata",
    "EvaluatorLaneState",
    "KING_STATE_FILENAME",
    "KING_STATE_SCHEMA_VERSION",
    "LANES_DIRNAME",
    "LANE_METADATA_FILENAME",
    "LANE_METADATA_SCHEMA_VERSION",
    "LaneKingState",
    "PACK_REGISTRY_FILENAME",
    "PACK_REGISTRY_SCHEMA_VERSION",
    "PROMOTION_RECORD_FILENAME",
    "PROMOTION_RECORD_SCHEMA_VERSION",
    "PackRegistry",
    "PackRegistryEntry",
    "PromotionRecord",
    "benchmark_snapshot_path",
    "challenge_state_path",
    "discover_active_lane_ids",
    "float_list_map",
    "int_map",
    "lane_king_state_path",
    "lane_metadata_path",
    "list_lane_ids",
    "load_benchmark_snapshot",
    "load_challenge_state",
    "load_evaluator_lane_state",
    "load_lane_king_state",
    "load_lane_metadata",
    "load_pack_registry",
    "load_promotion_record",
    "maybe_load",
    "optional_string",
    "pack_registry_path",
    "parse_benchmark_snapshot",
    "parse_challenge_state",
    "parse_lane_king_state",
    "parse_lane_metadata",
    "parse_pack_registry",
    "parse_promotion_record",
    "promotion_record_path",
    "read_json",
    "read_subnet_pack_field",
    "require_bool",
    "resolve_lane_root",
    "resolve_lanes_root",
    "serialize_lane_metadata",
    "serialize_pack_registry",
    "string_list",
    "sync_pack_registry",
    "upsert_pack_registry_entry",
    "validate_lane_id",
    "write_benchmark_snapshot",
    "write_challenge_state",
    "write_json_dataclass",
    "write_lane_king_state",
    "write_lane_metadata",
    "write_pack_registry",
    "write_promotion_record",
]
